volumes:
  app_tracker_local_postgres_data: {}
  app_tracker_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: app_tracker_local_django
    container_name: app_tracker_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: app_tracker_production_postgres
    container_name: app_tracker_local_postgres
    volumes:
      - app_tracker_local_postgres_data:/var/lib/postgresql/data
      - app_tracker_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: app_tracker_local_mailpit
    ports:
      - '8025:8025'

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: app_tracker_local_node
    container_name: app_tracker_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
